name: CI/CD for hosting a Flask-based Python Web Application

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  # Step 1: Install dependencies, run tests, and build on the GitHub Runner (not on EC2)
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Only check out code once

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installs dependencies, including pytest from requirements.txt

      - name: Run unit tests
        working-directory: ${{ github.workspace }}  # Ensure pytest runs from the repo root
        run: |
          pytest  # Run the pytest tests
        env:
          CI: true

      - name: Build the application
        run: |
          echo "Building the application"  # Placeholder for future build commands

  # Step 2: Deploy the latest code to EC2 Instance with Error Handling
  deploy-ec2:
    runs-on: ubuntu-latest
    needs: test-and-build
    steps:
      - name: Deploy the latest code to EC2 Instance
        run: |
          # Create the .ssh directory
          mkdir -p ~/.ssh
    
          # Write the private key to the id_rsa file
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
    
          # Ensure the private key has correct permissions
          chmod 600 ~/.ssh/id_rsa
    
          # SSH into the EC2 instance and deploy the application
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            # Enable error handling
            set -e
  
            echo "Starting deployment..."
  
            # Remove the SimpleFlaskApp directory if it exists and clone the repository
            if [ -d "/home/ubuntu/SimpleFlaskApp" ]; then
              echo "Removing existing SimpleFlaskApp directory..."
              rm -rf /home/ubuntu/SimpleFlaskApp || { echo "Failed to remove existing directory"; exit 1; }
            fi
  
            # Clone the repository
            git clone https://github.com/arpit1605/SimpleFlaskApp.git /home/ubuntu/SimpleFlaskApp || { echo "Git clone failed"; exit 1; }
  
            cd /home/ubuntu/SimpleFlaskApp
  
            # Set up logging after the directory is created
            LOG_FILE="/home/ubuntu/SimpleFlaskApp/deploy.log"
            exec > >(tee -a $LOG_FILE) 2>&1
  
            echo "Pulling latest changes from dev branch..."
            git pull origin dev || { echo "Git pull failed"; exit 1; }
  
            # Setting up virtual environment
            echo "Setting up virtual environment..."
            if [ -d "venv" ]; then
              source venv/bin/activate
            else
              python3 -m venv venv && source venv/bin/activate || { echo "Failed to create/activate virtual environment"; exit 1; }
            fi
  
            # Install dependencies
            echo "Installing dependencies..."
            pip install -r requirements.txt || { echo "Failed to install dependencies"; exit 1; }
  
            # Start Flask application with nohup and disown it
            echo "Starting Flask application..."
            nohup python app.py --host=0.0.0.0 > flask.log 2>&1 &
            disown
  
            # Check if Flask app started successfully
            sleep 5
            if pgrep -f "python app.py" > /dev/null
            then
              echo "Flask application started successfully"
            else
              echo "Failed to start Flask application" >&2
              exit 1
            fi
  
          EOF
        env:
          EC2_IP: ${{ secrets.EC2_IP }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
