name: CI/CD for hosting a Flask based Python Web Application

on:
  push:
    branches:
      - main
      - dev
  release:
    types: [published]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
  run-tests:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Run unit tests
        run: |
          pytest
        env:
          CI: true

  build-application:
    runs-on: ubuntu-latest
    needs: run-tests
    if: success() 
    steps:
      - name: Build the application
        run: echo "Building the application"

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-application
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Deploy to EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_KEY }} ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          cd ~/SimpleFlaskApp
          git pull origin dev
          source venv/bin/activate
          pip install -r requirements.txt
          nohup python app.py &
          EOF
        env:
          EC2_IP: ${{ secrets.EC2_IP }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
